In [1]:
import torch

In [47]:
a = torch.randn((9, 3))

In [48]:
print(a)

tensor([[-1.1670,  0.5806, -1.5908],
        [ 0.2985, -0.3564,  1.0317],
        [ 0.0365,  0.3392, -0.8458],
        [ 1.3202, -2.5964,  0.6469],
        [-0.4819,  0.9627, -0.1110],
        [ 0.3606,  0.4198,  2.1696],
        [ 0.5945, -0.5221, -1.0432],
        [-0.0383, -0.0352, -0.8681],
        [ 1.3339, -0.7215, -0.7266]])


In [51]:
a.cuda()-1.0

tensor([[-2.1670, -0.4194, -2.5908],
        [-0.7015, -1.3564,  0.0317],
        [-0.9635, -0.6608, -1.8458],
        [ 0.3202, -3.5964, -0.3531],
        [-1.4819, -0.0373, -1.1110],
        [-0.6394, -0.5802,  1.1696],
        [-0.4055, -1.5221, -2.0432],
        [-1.0383, -1.0352, -1.8681],
        [ 0.3339, -1.7215, -1.7266]], device='cuda:0')

In [50]:
(a.cuda()-1.0).long()

tensor([[-2,  0, -2],
        [ 0, -1,  0],
        [ 0,  0, -1],
        [ 0, -3,  0],
        [-1,  0, -1],
        [ 0,  0,  1],
        [ 0, -1, -2],
        [-1, -1, -1],
        [ 0, -1, -1]], device='cuda:0')

In [41]:
b = torch.randn((3, 3))
print(b)
print(b.size())

tensor([[-0.1428,  1.9910,  1.0452],
        [ 0.5195,  1.2930, -2.0958],
        [ 0.2188,  0.5346,  0.7148]])
torch.Size([3, 3])


In [42]:
b

tensor([[-0.1428,  1.9910,  1.0452],
        [ 0.5195,  1.2930, -2.0958],
        [ 0.2188,  0.5346,  0.7148]])

In [40]:
b.unsqueeze(0)

tensor([[[ 0.9085,  0.1791,  0.1699],
         [ 1.1165, -0.3787, -0.4030],
         [ 0.3072,  0.3901,  0.4899]]])

In [44]:
c=torch.repeat_interleave(b.cuda(), repeats=torch.tensor([2, 4, 3]).cuda(), dim=0)

In [46]:
print(c)

tensor([[-0.1428,  1.9910,  1.0452],
        [-0.1428,  1.9910,  1.0452],
        [ 0.5195,  1.2930, -2.0958],
        [ 0.5195,  1.2930, -2.0958],
        [ 0.5195,  1.2930, -2.0958],
        [ 0.5195,  1.2930, -2.0958],
        [ 0.2188,  0.5346,  0.7148],
        [ 0.2188,  0.5346,  0.7148],
        [ 0.2188,  0.5346,  0.7148]], device='cuda:0')


In [45]:
print(a)

tensor([[ 2.0011, -0.0325,  0.5785],
        [ 0.3196, -0.5192, -1.7581],
        [-0.7026, -0.2435,  0.6680],
        [ 1.3151, -1.2109, -2.1068],
        [ 0.3079,  0.3630,  0.0927],
        [ 0.3705, -0.2366,  1.0386],
        [ 0.7515, -1.4720,  1.1032],
        [ 0.0110,  0.2586, -0.6078],
        [-0.7980, -0.8207,  0.1848]])


In [34]:
chunk_size_list = torch.tensor([2, 4, 3])
print(chunk_size_list)
chunk_size_list = [2, 4, 3]

tensor([2, 4, 3])


In [35]:
chunk_list = torch.split(a, split_size_or_sections=chunk_size_list, dim=0)

In [10]:
torch.nn.utils.rnn.pad_sequence(chunk_list, batch_first=True)

tensor([[[-0.3766,  0.6445,  0.3259],
         [-1.3413,  0.9711,  0.7166],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000]],

        [[ 0.8157, -0.8397,  1.2337],
         [ 0.4120, -0.5992, -1.0866],
         [-0.8140,  0.7608,  0.0100],
         [-0.1946,  0.2819,  1.7048]],

        [[-0.2292, -0.5125,  1.4070],
         [ 0.5587,  0.3426, -0.8609],
         [-1.7520,  0.3980, -0.4850],
         [ 0.0000,  0.0000,  0.0000]]])

In [11]:
chunk_list

(tensor([[-0.3766,  0.6445,  0.3259],
         [-1.3413,  0.9711,  0.7166]]), tensor([[ 0.8157, -0.8397,  1.2337],
         [ 0.4120, -0.5992, -1.0866],
         [-0.8140,  0.7608,  0.0100],
         [-0.1946,  0.2819,  1.7048]]), tensor([[-0.2292, -0.5125,  1.4070],
         [ 0.5587,  0.3426, -0.8609],
         [-1.7520,  0.3980, -0.4850]]))

In [52]:
from torch.optim import SGD
from torch.optim.lr_scheduler import LambdaLR
from torchvision.models import resnet18

In [54]:
def poly_scheduler(epoch, num_epochs=300, power=0.9):
    print("epoch", epoch)
    return (1-epoch/num_epochs)**power

model = resnet18()
optimizer = SGD(model.parameters(), lr=0.001)
lr_scheduler = LambdaLR(optimizer=optimizer, lr_lambda=poly_scheduler)

for epoch in range(300):
    lr_scheduler.step()
    print("learning rate:{:.6f}".format(optimizer.param_groups[0]['lr']))
    optimizer.zero_grad()

epoch 0
epoch 1
learning rate:0.000997
epoch 2
learning rate:0.000994
epoch 3
learning rate:0.000991
epoch 4
learning rate:0.000988
epoch 5
learning rate:0.000985
epoch 6
learning rate:0.000982
epoch 7
learning rate:0.000979
epoch 8
learning rate:0.000976
epoch 9
learning rate:0.000973
epoch 10
learning rate:0.000970
epoch 11
learning rate:0.000967
epoch 12
learning rate:0.000964
epoch 13
learning rate:0.000961
epoch 14
learning rate:0.000958
epoch 15
learning rate:0.000955
epoch 16
learning rate:0.000952
epoch 17
learning rate:0.000949
epoch 18
learning rate:0.000946
epoch 19
learning rate:0.000943
epoch 20
learning rate:0.000940
epoch 21
learning rate:0.000937
epoch 22
learning rate:0.000934
epoch 23
learning rate:0.000931
epoch 24
learning rate:0.000928
epoch 25
learning rate:0.000925
epoch 26
learning rate:0.000922
epoch 27
learning rate:0.000919
epoch 28
learning rate:0.000916
epoch 29
learning rate:0.000913
epoch 30
learning rate:0.000910
epoch 31
learning rate:0.000907
epoch 32


In [55]:
import torch

In [63]:
a = torch.randn((2, 4, 3))

In [64]:
a

tensor([[[ 0.3376,  0.5404,  1.4118],
         [ 0.9021,  0.7833,  0.3959],
         [-0.7176,  0.0132, -0.5202],
         [ 0.4959,  0.4361, -1.0407]],

        [[-0.6083, -0.9036, -1.8689],
         [-0.4350, -0.3950, -0.0119],
         [-0.4589, -0.0028,  0.4012],
         [-1.0823, -0.1478, -0.9523]]])

In [65]:
x = torch.arange(2)

In [66]:
y = torch.arange(2)

In [69]:
a[x, y, :].squeeze(1)

tensor([[ 0.3376,  0.5404,  1.4118],
        [-0.4350, -0.3950, -0.0119]])

In [68]:
x, y

(tensor([0, 1]), tensor([0, 1]))