In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable

In [14]:
batch_size = 4
max_length = 3
hidden_size = 2
n_layers =1
feature_dim = 1

# container
batch_in = torch.zeros((batch_size, max_length, feature_dim))

# data
vec_1 = torch.FloatTensor([[1, 2, 3]]).reshape(-1, 1)
vec_2 = torch.FloatTensor([[1, 2, 0]]).reshape(-1, 1)
vec_3 = torch.FloatTensor([[1, 0, 0]]).reshape(-1, 1)
vec_4 = torch.FloatTensor([[2, 0, 0]]).reshape(-1, 1)

batch_in[0] = vec_1
batch_in[1] = vec_2
batch_in[2] = vec_3
batch_in[3] = vec_4

batch_in = Variable(batch_in)
print(batch_in)
print(batch_in.size())
seq_lengths = [3,2,1,1] # list of integers holding information about the batch size at each sequence step

batch_in = batch_in.transpose(0, 1)
print("batch_in size", batch_in.size())
# pack it
pack = torch.nn.utils.rnn.pack_padded_sequence(batch_in, seq_lengths)
print(pack)

rnn = nn.RNN(feature_dim, hidden_size, n_layers) 
h0 = Variable(torch.randn(n_layers, batch_size, hidden_size))

#forward 
out, hidden = rnn(pack, h0)

# unpack
unpacked, unpacked_len = torch.nn.utils.rnn.pad_packed_sequence(out)
print(unpacked)

tensor([[[1.],
         [2.],
         [3.]],

        [[1.],
         [2.],
         [0.]],

        [[1.],
         [0.],
         [0.]],

        [[2.],
         [0.],
         [0.]]])
torch.Size([4, 3, 1])
batch_in size torch.Size([3, 4, 1])
PackedSequence(data=tensor([[1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [3.]]), batch_sizes=tensor([4, 2, 1]))
tensor([[[ 0.8658, -0.6573],
         [ 0.5629, -0.5312],
         [ 0.3903, -0.4616],
         [ 0.5527, -0.7933]],

        [[ 0.7604, -0.8838],
         [ 0.8210, -0.8946],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[ 0.9243, -0.9757],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]]], grad_fn=<CopySlices>)


In [15]:
hidden[-1]

tensor([[ 0.9243, -0.9757],
        [ 0.8210, -0.8946],
        [ 0.3903, -0.4616],
        [ 0.5527, -0.7933]], grad_fn=<SelectBackward>)

In [22]:
batch_size = 4
max_length = 3
hidden_size = 2
n_layers =1
feature_dim = 1

# container
batch_in = torch.zeros((batch_size, max_length, feature_dim))

# data
vec_1 = torch.FloatTensor([[1, 2, 3]]).reshape(-1, 1)
vec_2 = torch.FloatTensor([[1, 2, 0]]).reshape(-1, 1)
vec_3 = torch.FloatTensor([[1, 0, 0]]).reshape(-1, 1)
vec_4 = torch.FloatTensor([[2, 0, 0]]).reshape(-1, 1)

batch_in[0] = vec_1
batch_in[1] = vec_2
batch_in[2] = vec_3
batch_in[3] = vec_4

batch_in = Variable(batch_in)
print(batch_in)
print(batch_in.size())
seq_lengths = [3,2,1,1] # list of integers holding information about the batch size at each sequence step

# batch_in = batch_in.transpose(0, 1)
# pack it
pack = torch.nn.utils.rnn.pack_padded_sequence(batch_in, seq_lengths, batch_first=True)
print(pack)

rnn = nn.RNN(feature_dim, hidden_size, n_layers, batch_first=True) 
h0 = Variable(torch.randn(n_layers, batch_size, hidden_size))

#forward 
out, hidden = rnn(pack, h0)

# unpack
unpacked, unpacked_len = torch.nn.utils.rnn.pad_packed_sequence(out)
print(unpacked)

tensor([[[1.],
         [2.],
         [3.]],

        [[1.],
         [2.],
         [0.]],

        [[1.],
         [0.],
         [0.]],

        [[2.],
         [0.],
         [0.]]])
torch.Size([4, 3, 1])
PackedSequence(data=tensor([[1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [3.]]), batch_sizes=tensor([4, 2, 1]))
tensor([[[-0.0502, -0.9329],
         [-0.3148, -0.1893],
         [-0.2821, -0.6359],
         [ 0.3024, -0.9997]],

        [[-0.1697, -0.9893],
         [-0.3221, -0.9655],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[-0.4234, -0.9962],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]]], grad_fn=<CopySlices>)


In [23]:
hidden[-1]

tensor([[-0.4234, -0.9962],
        [-0.3221, -0.9655],
        [-0.2821, -0.6359],
        [ 0.3024, -0.9997]], grad_fn=<SelectBackward>)

In [20]:
unpacked, unpacked_len = torch.nn.utils.rnn.pad_packed_sequence(out, batch_first=True)
print(unpacked)

tensor([[[-0.5015, -0.5813],
         [-0.5036,  0.1095],
         [-0.7585, -0.1988]],

        [[-0.2955, -0.5396],
         [-0.5320,  0.0787],
         [ 0.0000,  0.0000]],

        [[-0.2170,  0.1340],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[-0.4763,  0.2694],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]]], grad_fn=<TransposeBackward0>)


In [41]:
a = torch.randn(3)
a[0] = 1.9939
print("a", a)

a tensor([1.9939, 0.1828, 0.1520])


In [42]:
a = a.view(-1, 1)
print(a)

tensor([[1.9939],
        [0.1828],
        [0.1520]])


In [43]:
b = torch.randn((3, 4))
print(b)
b[0, 1] = 1.9939
print(b)

tensor([[ 1.1926, -1.1970, -0.8094,  0.6168],
        [-1.1353, -2.6595, -0.0865,  0.1778],
        [ 0.7685, -0.5173, -0.2906, -1.1883]])
tensor([[ 1.1926,  1.9939, -0.8094,  0.6168],
        [-1.1353, -2.6595, -0.0865,  0.1778],
        [ 0.7685, -0.5173, -0.2906, -1.1883]])


In [44]:
a = a.expand_as(b)
print(a)

tensor([[1.9939, 1.9939, 1.9939, 1.9939],
        [0.1828, 0.1828, 0.1828, 0.1828],
        [0.1520, 0.1520, 0.1520, 0.1520]])


In [45]:
c = (a == b)

In [46]:
c

tensor([[0, 1, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)

In [51]:
d = c.nonzero()
print(d)

tensor([[0, 1]])


In [53]:
d[:, :-1]

tensor([[0]])

In [57]:
a = 1000
b = 10
a//b

100

In [58]:
print(a)

1000


In [59]:
a = torch.randn(20)

In [60]:
print(a)

tensor([-0.4823, -1.9368,  0.2392,  1.0779,  0.5600, -1.1144, -0.4890, -0.1504,
        -2.4804, -1.2565, -2.1945, -0.2593,  0.4618, -1.0432, -0.8223, -0.9411,
         0.8311,  1.0022, -0.3361, -0.3670])


In [65]:
a.view(-1).size(0)

20

In [67]:
import pandas as pd

In [68]:
df = pd.DataFrame(columns=['raw_itemid', 'itemid', 'num'])


In [69]:
df.loc[0] = [1, 1, 3]

In [70]:
df

raw_itemid itemid num
0          1      1   3

In [71]:
if 2 not in df.itemid:
    print("error", 2)
    df.loc[1] = [2, 2, 5]
print(df)

error 2
  raw_itemid itemid num
0          1      1   3
1          2      2   5


In [72]:
len(df)

2

In [88]:
df.loc[df.itemid==2, 'num'] += 1

In [89]:
df

raw_itemid  itemid  num
0           1       1    3
1           2       2    7

In [105]:
set(df.itemid.to_list())-set([2])

{1}

In [96]:
a = df.num**0.01
a = a.cumsum()/a.sum()

In [99]:
print(a.values)

[0.49788177 1.        ]


In [93]:
import numpy as np
np.searchsorted([1,2,6,4,3], 5)

2

In [ ]:
sorted_df = df.sort_values(by=['userid', 'timestamp'], ascending=[True, True])

In [175]:
a = np.array([[1, 2, 5, 6], [3, 4, 7, 8], [10, 20, 30, 40], [90, 100, 800, 900]])

In [176]:
a.shape

(4, 4)

In [177]:
b = np.array([[1, 2], [2, 3], [3, 0], [1, 0]])

b.shape

(4, 2)

In [178]:
c = np.arange(4)
c = c.reshape(-1, 1)
print(c)

[[0]
 [1]
 [2]
 [3]]


In [179]:
a[c, b]

array([[  2,   5],
       [  7,   8],
       [ 40,  10],
       [100,  90]])

In [151]:
a = {"ac":1, "bd":2}
b = {"ac":7}
c_df = pd.DataFrame([a, b]).T

In [152]:
print(c_df)

      0    1
ac  1.0  7.0
bd  2.0  NaN


In [153]:
c_df['index'] = a.keys()

In [156]:
c_df

0    1 index
ac  1.0  7.0    ac
bd  2.0  NaN    bd

In [157]:
c_df.columns=['cl1', 'cl2', 'index']

In [158]:
c_df

cl1  cl2 index
ac  1.0  7.0    ac
bd  2.0  NaN    bd

In [159]:
c_df['index'] = c_df.index

In [160]:
c_df

cl1  cl2 index
ac  1.0  7.0    ac
bd  2.0  NaN    bd

In [134]:
d = dict(sorted(a.items(), key=lambda item: item[0]))

In [140]:
np.array(d.values())

array(dict_values([2, 1]), dtype=object)

In [161]:
a = np.array([1, 2])

In [163]:
a.shape[0]

2

In [164]:
a = {"name":[1, 2, 3, 4], "val":[10, 50, 100, 500]}
b = {"name":[1, 2, 3, 4], "raw_val":[7, 8, 9, 10]}

In [165]:
c_df = pd.DataFrame([a, b])

In [166]:
c_df

name        raw_val                 val
0  [1, 2, 3, 4]            NaN  [10, 50, 100, 500]
1  [1, 2, 3, 4]  [7, 8, 9, 10]                 NaN

In [172]:
df = pd.DataFrame(columns=['itemid', 'col1', 'col2'])
a = {"c":10, "a": 1, "b":2}
b = {"a":7, "b":10}

In [173]:
df.itemid = a.keys()

In [174]:
df.col1 = a.values()
df.col2 = b.values()

ValueError: Length of values does not match length of index

In [171]:
df

itemid  col1  col2
0      a     1     7
1      b     2    10